no change

diff --git a/.github/workflows/merge-to-devBranch.yml b/.github/workflows/merge-to-devBranch.yml
--- a/.github/workflows/merge-to-devBranch.yml
+++ b/.github/workflows/merge-to-devBranch.yml
@@ -23,7 +23,17 @@ jobs:
         with:
           fetch-depth: 0
 
-    
+      # Scan for System.debug in the codebase
+      - name: "Scan for System.debug Logs"
+        run: |
+          echo "Scanning for System.debug logs in the codebase..."
+          if grep -r "System.debug" force-app/; then
+            echo "Error: System.debug statements found in the codebase!"
+            exit 1
+          else
+            echo "No System.debug logs found. Validation passed!"
+          fi
+        shell: bash
 
   # Step 2: Merge PR if validation passed
   merge-pr:
@@ -32,8 +42,8 @@ jobs:
     if: github.event.pull_request.merged == false
     steps:
       # Merge the PR into the main branch
-      - name: Auto Merge PR
-        uses: "peter-etc'authentication!"
+      - name: "Merge Pull Request"
+        uses: ahmadnassri/action-auto-merge@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
